version: '3.8'

services:
    django:
        restart: always
        build: .
        # сборка находится в том-же катклоге
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/docker_app
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
#            - pgdb
            - redis
    celery:
        restart: always
        build: .
        command: celery -A core worker -E -l INFO
        volumes:
            - .:/docker_app
        depends_on:
            - django
            - redis
#    pgdb:
#        restart: always
#        image: postgres
#        container_name: pgdb
#        environment:
#            - POSTGRES_DB=postgres
#            - POSTGRES_USER=postgres
#            - POSTGRES_PASSWORD=postgres
#        volumes:
#            - pgdata:/var/lib/postgresql/data/
    redis:
        image: 'redis:alpine'

volumes:
    pgdata:


